from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from .models import AssemblyManual, AssemblyStep, ReferenceMedia


def _required(data: dict[str, Any], key: str, where: str) -> Any:
    value = data.get(key)
    if value is None or value == "":
        raise ValueError(f"{where}: '{key}' 값이 필요합니다")
    return value


def load_manual(path: str | Path) -> AssemblyManual:
    """Load and minimally validate an assembly manual YAML file."""
    source = Path(path).resolve()
    raw = yaml.safe_load(source.read_text(encoding="utf-8")) or {}
    steps: list[AssemblyStep] = []
    seen: set[str] = set()
    for index, item in enumerate(raw.get("steps", ())):
        where = f"steps[{index}]"
        step_id = str(_required(item, "id", where))
        if step_id in seen:
            raise ValueError(f"중복 단계 ID: {step_id}")
        seen.add(step_id)
        refs = item.get("references") or {}
        images = tuple(_resolve_media(source.parent, value) for value in refs.get("images", ()))
        videos = tuple(_resolve_video(source.parent, value) for value in refs.get("videos", ()))
        steps.append(AssemblyStep(
            id=step_id,
            order=int(item.get("order", index + 1)),
            title=str(_required(item, "title", where)),
            instruction=str(_required(item, "instruction", where)),
            required_parts=tuple(item.get("required_parts", ())),
            required_tools=tuple(item.get("required_tools", ())),
            safety_notes=tuple(item.get("safety_notes", ())),
            preconditions=tuple(item.get("preconditions", ())),
            completion_conditions=tuple(item.get("completion_conditions", ())),
            error_conditions=tuple(item.get("error_conditions", ())),
            visual_checks=tuple(item.get("visual_checks") or _derived_visual_checks(item)),
            visual_state=dict(item.get("visual_state") or {}),
            references=ReferenceMedia(images=images, videos=videos),
        ))
    if not steps:
        raise ValueError("매뉴얼에는 최소 한 단계가 필요합니다")
    steps.sort(key=lambda step: step.order)
    return AssemblyManual(
        manual_id=str(_required(raw, "manual_id", "manual")),
        product=str(_required(raw, "product", "manual")),
        version=str(_required(raw, "version", "manual")),
        description=str(raw.get("description", "")),
        parts=tuple(raw.get("parts", ())),
        tools=tuple(raw.get("tools", ())),
        steps=tuple(steps),
    )


def _derived_visual_checks(step: dict[str, Any]) -> list[dict[str, Any]]:
    """Backfill deterministic IDs for manuals generated by older versions."""
    visual = step.get("visual_state") or {}
    checks: list[dict[str, Any]] = []
    for index, description in enumerate(visual.get("new_elements", ())):
        checks.append({"id": f"visual_element_{index + 1:02d}", "kind": "required",
                       "description": str(description), "required": True})
    for index, description in enumerate(visual.get("spatial_relations", ())):
        checks.append({"id": f"visual_relation_{index + 1:02d}", "kind": "required",
                       "description": str(description), "required": True})
    for condition in step.get("error_conditions", ()):
        if condition.get("type") == "vision_review":
            checks.append({"id": str(condition.get("id", "visual_error")),
                           "kind": "error", "description": str(condition.get("description", "")),
                           "required": False})
    return checks


def _resolve_media(root: Path, value: Any) -> str:
    path = Path(str(value))
    return str(path if path.is_absolute() else (root / path).resolve())


def _resolve_video(root: Path, value: Any) -> dict[str, Any]:
    item = dict(value) if isinstance(value, dict) else {"file": str(value)}
    item["file"] = _resolve_media(root, item["file"])
    return item
